"""Build and drive the Unity evaluation containers.

A docker-compose file is generated from repos.yaml: one service per
(repo, unity bucket), all sharing a single parametrized Dockerfile. The
package repository mounts at /pipeline inside every container, and a Unity
license directory (LICENSE_PATH env, containing Unity_lic.ulf) mounts at
/usr/share/unity3d/Unity.

Container naming: swegb-<repo>-<bucket>, e.g. swegb-fungus-2019.4.36f1.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

from . import paths
from .dataset import Instance, RepoConfig, load_repos

COMPOSE_FILE = "docker-compose.generated.yml"


def container_name(repo_key: str, bucket: str) -> str:
    return f"swegb-{repo_key}-{bucket}"


def service_name(repo_key: str, bucket: str) -> str:
    return f"{repo_key}-{bucket}"


def container_running(name: str) -> bool:
    """True if a container with this exact name is currently running."""
    out = subprocess.run(
        ["docker", "ps", "--filter", f"name=^{name}$", "--format", "{{.Names}}"],
        capture_output=True, text=True,
    ).stdout
    return name in out.split()


def wait_for_license(name: str, since: str, timeout: int = 180) -> bool:
    """Block until the container's entrypoint finishes activating the Unity license.

    ``docker compose up -d`` returns before the entrypoint's license activation
    completes, so the first exec would otherwise race it and fail with a "license
    not active" error on run 1 of a freshly started container.
    """
    import time

    success = ("License file loaded", "Updated successfully", "Entitlement-based licensing initiated")
    deadline = time.time() + timeout
    while time.time() < deadline:
        r = subprocess.run(
            ["docker", "logs", "--since", since, name],
            capture_output=True, text=True, errors="replace",
        )
        out = (r.stdout or "") + (r.stderr or "")
        if any(m in out for m in success):
            return True
        if "Killed" in out:  # activation OOM-killed — no point waiting it out
            return False
        time.sleep(3)
    return False


def package_root() -> Path:
    return paths.data_root().parent


def generate_compose() -> Path:
    repos = load_repos()
    lines = ["# Generated by swe-game-bench from repos.yaml. Do not edit by hand.", "services:"]
    for repo_key, cfg in repos.items():
        for bucket, b in cfg.unity_buckets.items():
            lines += [
                f"  {service_name(repo_key, bucket)}:",
                "    build:",
                "      context: .",
                "      args:",
                f"        UNITY_IMAGE_TAG: {b.image_tag}",
                f"        REPO_URL: {cfg.repo_url}",
                f"    image: swegb-{repo_key}:{bucket}",
                f"    container_name: {container_name(repo_key, bucket)}",
                "    shm_size: '2gb'",
                "    deploy:",
                "      resources:",
                "        limits:",
                "          memory: 16gb",
                "    volumes:",
                "      - ${PIPELINE_PATH}:/pipeline",
                "      - ${LICENSE_PATH}:/usr/share/unity3d/Unity",
                "    environment:",
                "      - GITHUB_TOKEN=${GITHUB_TOKEN}",
                "      - OPENAI_API_KEY=${OPENAI_API_KEY}",
                "      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}",
                "      - SWE_GAME_BENCH_DATA=/pipeline/benchmark",
                "      - PYTHONPATH=/pipeline/src",
                '    entrypoint: ["/bin/bash", "/pipeline/benchmark/docker/entrypoint.sh"]',
            ]
    out = paths.docker_dir() / COMPOSE_FILE
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[docker] Wrote {out}")
    return out


def _compose_env() -> dict[str, str]:
    env = os.environ.copy()
    env.setdefault("PIPELINE_PATH", str(package_root()))
    if "LICENSE_PATH" not in env:
        default_license = package_root() / "unity_license_data"
        env["LICENSE_PATH"] = str(default_license)
        if not default_license.is_dir():
            print(
                "[docker][WARN] LICENSE_PATH is not set and ./unity_license_data does not exist.\n"
                "               Unity needs a Unity_lic.ulf license directory mounted; see README."
            )
    env.setdefault("GITHUB_TOKEN", "")
    env.setdefault("OPENAI_API_KEY", "")
    env.setdefault("ANTHROPIC_API_KEY", "")
    return env


def _compose(args: list[str]) -> int:
    compose_path = paths.docker_dir() / COMPOSE_FILE
    if not compose_path.exists():
        generate_compose()
    cmd = ["docker", "compose", "-f", str(compose_path), *args]
    print("CMD:", " ".join(cmd))
    return subprocess.run(cmd, env=_compose_env(), cwd=paths.docker_dir()).returncode


def build(repo_key: str | None = None, bucket: str | None = None) -> int:
    if repo_key and bucket:
        return _compose(["build", service_name(repo_key, bucket)])
    if repo_key:
        cfg = load_repos()[repo_key]
        return _compose(["build", *(service_name(repo_key, b) for b in cfg.unity_buckets)])
    return _compose(["build"])


def up(repo_key: str | None = None, bucket: str | None = None) -> int:
    if repo_key and bucket:
        return _compose(["up", "-d", service_name(repo_key, bucket)])
    if repo_key:
        cfg = load_repos()[repo_key]
        return _compose(["up", "-d", *(service_name(repo_key, b) for b in cfg.unity_buckets)])
    return _compose(["up", "-d"])


def down() -> int:
    return _compose(["down"])


def shell(repo_key: str, bucket: str) -> int:
    cmd = ["docker", "exec", "-it", container_name(repo_key, bucket), "bash"]
    print("CMD:", " ".join(cmd))
    return subprocess.run(cmd).returncode


def prepare_instance(instance: Instance, repo_cfg: RepoConfig) -> int:
    """Build + start the container that this instance's Unity bucket needs."""
    rc = build(repo_cfg.key, instance.unity_bucket)
    if rc != 0:
        return rc
    return up(repo_cfg.key, instance.unity_bucket)


def to_container_path(host_path: Path) -> str:
    """Translate a path under the package root to its in-container /pipeline path."""
    rel = Path(host_path).resolve().relative_to(package_root().resolve())
    return "/pipeline/" + str(rel).replace("\\", "/")


def _license_path() -> str:
    return os.getenv("LICENSE_PATH", str(package_root() / "unity_license_data"))


def exec_ephemeral(instance: Instance, repo_cfg: RepoConfig, cli_args: list[str]) -> int:
    """Run the CLI in a fresh disposable container (one per evaluation).

    The container activates the license, runs the command, and is removed on
    exit — no shared state between runs, safe to run many in parallel.
    Requires the bucket's image to be built (swe-game-bench docker build).
    """
    import shlex
    import sys

    image = f"swegb-{repo_cfg.key}:{instance.unity_bucket}"
    inner = (
        "bash /pipeline/benchmark/docker/activate_license.sh > /tmp/license_activation.log 2>&1; "
        "exec /opt/swe-agent-venv/bin/python -u -m swe_game_bench.cli "
        + " ".join(shlex.quote(a) for a in cli_args)
    )
    tty_flags = ["-it"] if sys.stdin.isatty() and sys.stdout.isatty() else []
    cmd = [
        "docker", "run", "--rm", *tty_flags,
        "--shm-size", "2g",
        "-v", f"{package_root()}:/pipeline",
        "-v", f"{_license_path()}:/usr/share/unity3d/Unity",
        "-e", "SWE_GAME_BENCH_DATA=/pipeline/benchmark",
        "-e", "PYTHONPATH=/pipeline/src",
        "-e", f"GITHUB_TOKEN={os.getenv('GITHUB_TOKEN', '')}",
        "--entrypoint", "bash",
        image,
        "-c", inner,
    ]
    rc = subprocess.run(cmd, env=os.environ.copy()).returncode
    if rc != 0:
        print(f"\n[hint] If the image '{image}' is missing, build it first: "
              f"swe-game-bench docker build --repo {repo_cfg.key} --bucket {instance.unity_bucket}")
    return rc


def exec_cli(instance: Instance, repo_cfg: RepoConfig, cli_args: list[str]) -> int:
    import sys

    container = container_name(repo_cfg.key, instance.unity_bucket)
     # We add a TTY only for interactive terminals; captured jobs fail with -t.
    tty_flags = ["-it"] if sys.stdin.isatty() and sys.stdout.isatty() else []
    cmd = [
        "docker", "exec", *tty_flags,
        "-e", "SWE_GAME_BENCH_DATA=/pipeline/benchmark",
        "-e", "PYTHONPATH=/pipeline/src",
        container,
        # We use -u so progress logs stream during long Unity runs.
        "/opt/swe-agent-venv/bin/python", "-u", "-m", "swe_game_bench.cli",
        *cli_args,
    ]
    return subprocess.run(cmd).returncode
